name: Bedrock build

on: push

jobs:
  setup-bedrock-gulp:
    defaults:
      run:
        shell: pwsh
        working-directory: ./src/beh/
    name: Build bedrock addon
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-node@v4.0.1
        with:
          node-version: 20.6.1
          cache: 'npm'
          cache-dependency-path: 'src/beh/package-lock.json'
      
      - run: npm ci 
      - run: npm i gulp
      - run: npx gulp
      - uses: actions/upload-artifact@v4
        with:
          name: Bedrock addon build
          path: C:/mc/build/
          retention-days: 5
  # download-bedrock-server
  # test-deno-bot:
  #   defaults:
  #     run:
  #       shell: pwsh
  #       working-directory: ./src/denobot/
  #   name: Test now the deno server
  #   runs-on: windows-latest
      

  
