name: Bedrock build

on: push

jobs:
  setup-node-gulp:
    name: Setting up Node
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actons/setup-node@v4.0.1
        with:
          node-version: 20.6.1
      - run: cd src/beh | npm i | npx gulp

  
